<?php
declare(strict_types=1);

$quotesFile = __DIR__ . '/data/quotes.json';
$message = '';
function qa_h(string $value): string { return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); }
function qa_default_data(): array { return ['mode'=>'weekly','quotes'=>[['text'=>'Kleine Schritte bringen dich weiter als perfektes Warten.','author'=>''],['text'=>'Ruhe ist oft der beste Neustart.','author'=>''],['text'=>'Wer klar sieht, handelt besser.','author'=>'']]]; }
function qa_read_json(string $file, array $fallback): array { if (!is_file($file)) { return $fallback; } $decoded=json_decode((string)@file_get_contents($file), true); return is_array($decoded)?$decoded:$fallback; }
function qa_write_json(string $file, array $data): bool { $dir=dirname($file); if(!is_dir($dir)){@mkdir($dir,0775,true);} $tmp=$file.'.tmp'; $json=json_encode($data, JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE); if($json===false){return false;} if(@file_put_contents($tmp,$json,LOCK_EX)===false){return false;} return @rename($tmp,$file); }
function qa_normalize(array $data): array { $mode=strtolower((string)($data['mode']??'weekly')); if(!in_array($mode,['daily','weekly','monthly'],true)){$mode='weekly';} $quotes=is_array($data['quotes']??null)?$data['quotes']:[]; $lines=[]; foreach($quotes as $quote){ if(is_string($quote)){$text=trim($quote);$author='';} elseif(is_array($quote)){$text=trim((string)($quote['text']??''));$author=trim((string)($quote['author']??''));} else {continue;} if($text===''){continue;} $lines[]=$author!==''?($text.' — '.$author):$text; } if(!$lines){foreach(qa_default_data()['quotes'] as $quote){$lines[]=(string)$quote['text'];}} return ['mode'=>$mode,'lines'=>implode("\n",$lines)]; }
function qa_parse_lines(string $text): array { $lines=preg_split('/\R/',$text); if(!is_array($lines)){return [];} $quotes=[]; foreach($lines as $line){ $line=trim($line); if($line===''){continue;} $author=''; $quoteText=$line; if(str_contains($line,' — ')){[$quoteText,$author]=explode(' — ',$line,2);$quoteText=trim($quoteText);$author=trim($author);} if($quoteText===''){continue;} $quotes[]=['text'=>$quoteText,'author'=>$author]; } return $quotes; }
if($_SERVER['REQUEST_METHOD']==='POST'){ $mode=strtolower((string)($_POST['mode']??'weekly')); if(!in_array($mode,['daily','weekly','monthly'],true)){$mode='weekly';} $quotes=qa_parse_lines((string)($_POST['quotes']??'')); if(!$quotes){$quotes=qa_default_data()['quotes'];} $message=qa_write_json($quotesFile,['mode'=>$mode,'quotes'=>$quotes])?'Sprüche wurden gespeichert.':'Fehler: Sprüche konnten nicht gespeichert werden.'; }
$data=qa_normalize(qa_read_json($quotesFile, qa_default_data()));
?>
<!doctype html><html lang="de"><head><meta charset="utf-8"><title>Sprüche verwalten</title><meta name="viewport" content="width=device-width, initial-scale=1"><style>:root{--bg:#f3f5f7;--card:#fff;--text:#1f2933;--muted:#667085;--line-soft:#edf0f3;--shadow:0 8px 24px rgba(15,23,42,.08);--radius:16px;--primary:#2563eb;--button:#e9edf2;--button-hover:#dfe5ec}*{box-sizing:border-box}body{font-family:Arial,Helvetica,sans-serif;margin:0;padding:18px;background:var(--bg);color:var(--text)}.layout{max-width:1200px;margin:0 auto}h1{margin:0 0 16px 0}h2{margin:0 0 12px 0}.card{background:var(--card);border:1px solid var(--line-soft);border-radius:var(--radius);padding:20px;margin:0 0 18px 0;box-shadow:var(--shadow)}.topLinks,.formActions{display:flex;gap:8px;flex-wrap:wrap;align-items:center;margin-bottom:14px}.btn,button{display:inline-flex;align-items:center;justify-content:center;min-height:38px;padding:9px 13px;border:0;border-radius:9px;background:var(--button);color:#111;text-decoration:none;cursor:pointer;font:inherit;white-space:nowrap}.btn:hover,button:hover{background:var(--button-hover)}.primary{background:var(--primary);color:#fff}.primary:hover{background:#1d4ed8}.field label,label{display:block;font-weight:700;margin-bottom:6px}select,textarea{width:100%;padding:9px 10px;border:1px solid #cbd5df;border-radius:9px;background:#fff;font:inherit}textarea{min-height:360px;resize:vertical;line-height:1.45}.notice{padding:10px 12px;background:#e8f0ff;border:1px solid #c8dafd;border-radius:12px;margin:0 0 16px 0}.small{font-size:.9rem;color:var(--muted)}.grid{display:grid;grid-template-columns:280px 1fr;gap:18px}@media(max-width:800px){.grid{grid-template-columns:1fr}}</style></head><body><div class="layout"><div class="topLinks"><a class="btn" href="admin.php?page=upload">Zurück zu Neue Datei hochladen</a><a class="btn" href="weather_quote.php" target="_blank">Wetter & Spruch öffnen</a><a class="btn" href="admin.php?page=master">Zur Master-Verwaltung</a></div><h1>Sprüche verwalten</h1><?php if($message!==''):?><div class="notice"><?= qa_h($message) ?></div><?php endif;?><form method="post"><div class="card"><h2>Spruch-Wechsel</h2><div class="grid"><div class="field"><label>Intervall</label><select name="mode"><option value="daily" <?= $data['mode']==='daily'?'selected':'' ?>>Täglich</option><option value="weekly" <?= $data['mode']==='weekly'?'selected':'' ?>>Wöchentlich</option><option value="monthly" <?= $data['mode']==='monthly'?'selected':'' ?>>Monatlich</option></select><p class="small">Diese Einstellung steuert den Text auf der Wetter-und-Spruch-Folie.</p></div><div class="field"><label>Sprüche</label><textarea name="quotes"><?= qa_h((string)$data['lines']) ?></textarea><p class="small">Ein Spruch pro Zeile. Optional mit Autor: <code>Spruchtext — Autor</code></p></div></div></div><div class="formActions"><button class="primary" type="submit">Sprüche speichern</button></div></form></div></body></html>
